BI-8649 create additional information page
companieshouse/certificates.orders.web.ch.gov.uk pull request #196
Opened 2021-08-12 13:58 UTC by dlgroves-ch

* Change layout of registered office address options page if query parameter layout is set to 'full'.

Resolves:
[BI-8649](https://companieshouse.atlassian.net/browse/BI-8649)

2021-08-12 15:03 UTC, phudson-ch requested changes
Minor change to src/controllers/certificates/director.options.controller.ts:

Unused default import `e,` can be removed.

2021-08-12 16:06 UTC, phudson-ch approved these changes

2021-08-12 16:08 UTC, kinpang-CH approved these changes

2021-08-13 11:00 UTC, ethatcher83 approved these changes

2021-08-13 11:26 UTC, merged