BI-8848 Implement option filter on cert options page
companieshouse/certificates.orders.web.ch.gov.uk pull request #220
Opened 2021-11-25 17:30 UTC by dlgroves-ch

* Filter good standing option if company is in liquidation.
* Filter liquidators option if company is active.

Resolves:
[BI-8848](https://companieshouse.atlassian.net/browse/BI-8848)

2021-11-26 08:33 UTC, phudson-ch requested changes

2021-11-26 08:33 UTC, phudson-ch commented on test/controller/certificates/llp-certificates/options.controller.unit.test.ts
> +        it("should set includeBasicInformation on MemberDetails to true, when the option is liquidators", () => {
Should read: should set includeBasicInformation on LiquidatorsDetails...

2021-11-26 08:33 UTC, phudson-ch commented on src/controllers/certificates/options.controller.ts
> +                    itemOptionsAccum.liquidatorsDetails = { includeBasicInformation: true };
Missing property: add liquidatorsDetails property to ItemOptionsRequest

2021-11-26 09:14 UTC, dlgroves-ch commented on src/controllers/certificates/options.controller.ts
> +                    itemOptionsAccum.liquidatorsDetails = { includeBasicInformation: true };
TODO: If company status is liquidation, add field to ItemOptionsRequest.

2021-11-26 13:32 UTC, phudson-ch approved these changes

2021-11-29 11:29 UTC, dlgroves-ch commented on src/controllers/certificates/llp-certificates/options.controller.ts
> +                goodStanding: companyProfile.companyStatus != 'liquidation',
Use enum constants here.

2021-11-29 11:29 UTC, dlgroves-ch commented on src/controllers/certificates/llp-certificates/options.controller.ts
> +    if(companyStatus === "liquidation") {
Use enum constant here.

2021-11-29 11:29 UTC, dlgroves-ch commented on src/controllers/certificates/llp-certificates/options.controller.ts
> +                if(companyStatus === "liquidation"){
Use enum constant here.

2021-11-29 11:29 UTC, dlgroves-ch commented on src/controllers/certificates/options.controller.ts
> +                goodStanding: companyProfile.companyStatus != 'liquidation',
Use enum constant here.

2021-11-29 11:29 UTC, dlgroves-ch commented on src/controllers/certificates/options.controller.ts
> +    if(companyStatus === "liquidation") {
Use enum constant here.

2021-11-29 11:29 UTC, dlgroves-ch commented on src/controllers/certificates/options.controller.ts
> +                if(companyStatus === "liquidation"){
Use enum constant here.

2021-11-29 11:29 UTC, dlgroves-ch commented on test/controller/certificates/options.controller.unit.test.ts
> +        it("should leave multiple itemOptions to null if company is active and options are undefined", () => {
Fix wording

2021-11-29 11:29 UTC, dlgroves-ch commented on test/controller/certificates/llp-certificates/options.controller.unit.test.ts
> +            const returnedItemOptions = setItemOptions("active");
Fix wording of test case.

2021-11-29 11:44 UTC, phudson-ch approved these changes

2021-11-29 11:45 UTC, kinpang-CH approved these changes

2021-11-29 11:45 UTC, merged