BI-11398 navigate delivery options
companieshouse/certificates.orders.web.ch.gov.uk pull request #293
Opened 2022-08-05 07:39 UTC by aokunade

BI-11398 navigate delivery options

2022-08-05 08:29 UTC, ethatcher83 commented on src/controllers/certificates/delivery.options.controller.ts
> +        const expressCost =  "50";
Doesn't look like you are covering the output of these values for the error page

2022-08-05 08:29 UTC, ethatcher83 commented on src/controllers/certified-copies/delivery.options.controller.ts
> +            expressCost,
Doesn't look like you are covering the output of these values for the error page. I'd also suggest making these values all caps like DISPATCH_DAYS

2022-08-05 08:29 UTC, ethatcher83 commented on src/client/api.client.ts
> +export const patchCertifiedCopyItem = async (
Tests will need to be added to test this patch functionality

2022-08-05 08:29 UTC, ethatcher83 commented on src/controllers/certified-copies/delivery.options.controller.ts
> +import { NextFunction, Request, Response } from "express";
This controller will require test coverage

2022-08-05 08:36 UTC, hwilliams1 requested changes
Doesn't look like there are any unit tests on this. Can unit tests be added please?

2022-08-09 06:18 UTC, hwilliams1 approved these changes

2022-08-09 06:18 UTC, merged